# Generated by Django 4.0.1 on 2022-01-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=155)),
                ('slug', models.SlugField(max_length=155)),
                ('afbeelding', models.ImageField(upload_to='')),
                ('omschrijving', models.TextField()),
                ('datum', models.DateTimeField()),
            ],
        ),
    ]
