# Generated by Django 4.0.1 on 2022-01-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0002_acties'),
    ]

    operations = [
        migrations.AddField(
            model_name='producten',
            name='actief',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producten',
            name='slug',
            field=models.SlugField(default='', max_length=155),
        ),
        migrations.AlterField(
            model_name='producten',
            name='actieprijs',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='producten',
            name='prijs',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
